### PR TITLE
Register prompt on correct module

### PR DESCRIPTION
**Pull request by yaodingyd**
`autosubmit` is not working on the prompt instance but only working on `inquirer.prompt` which I used to test locally...

### CODE REVIEW

**Comment by yaodingyd** [comment]
@SamVerschueren bump on this. `0.2.0` is not working correctly because of wrong module registration.

**Comment by LuKks** [comment]
It will be great to see this merged.

**Comment by yaodingyd** [comment]
@SamVerschueren another bump

**Review by SamVerschueren — APPROVED** [review]

**Comment by SamVerschueren** [comment]
Sorry for the delay. I turned off my GitHub notifications so I easily miss things. Thanks @sindresorhus for pinging me.

**Comment by SamVerschueren** [comment]
Released as 0.2.1

**Pull request merged**
